version: '2'
services:
  ipfs-dameon-init:
    image: golang
    volumes:
      - ./go-ipfs:/ipfs
      - ./storage-ipfs:/storage
      - ./conf-ipfs:/conf
    environment:
      - PATH=/ipfs:$PATH
      - IPFS_PATH=/storage
    command: ipfs init
    restart: "no"
